version: '3.3'
services:
  elasticsearch:
    image: elasticsearch:6.5.1
    restart: always
    container_name: elasticsearch
    volumes:
      - /path/to/DockerData/elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
