version: '3.3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=db
      - MYSQL_USER=usr
      - MYSQL_PASSWORD=pwd
    volumes:
      - /path/to/DockerData/mysql/datadir:/var/lib/mysql
      - ./conf.d:/etc/mysql/conf.d
    ports:
      - 3306:3306
