version: '3.3'
services:
  redis:
    image: redis:4.0.11
    restart: always
    container_name: redis
    volumes:
      - /path/to/DockerData/redis/data:/data
    ports:
      - 6379:6379
    command: redis-server --requirepass redis
